builds:
  - binary: lokey
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: lokey
    homepage: "https://github.com/ThywillJoshua/lokey-cli"
    description: "A powerful CLI tool for managing Lokey operations"
    repository:
      owner: "thywilljoshua"
      name: "homebrew-lokey"
    commit_author:
      name: "Thywill Joshua"
      email: "thywilljoshua@gmail.com"
    dependencies:
      - go
    install: |
      bin.install "lokey"

checksum:
  name_template: "checksums.txt"
