builds:
  - binary: lokey-cli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: lokey
    homepage: https://github.com/ThywillJoshua/lokey-cli
    repository:
      owner: thywilljoshua
      name: homebrew-thywilljoshua
    commit_author:
      name: Thywill Joshua
      email: thywilljoshua@gmail.com
    description: "A powerful CLI tool for managing lokey operations"
    dependencies:
      - go
    install: |
      bin.install "lokey"

checksum:
  name_template: "checksums.txt"
