# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokey < Formula
  desc "A powerful CLI tool for managing lokey operations"
  homepage "https://github.com/ThywillJoshua/lokey-cli"
  version "0.2"

  depends_on "go"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.2/lokey-cli_0.2_linux_amd64.tar.gz"
      sha256 "1f46c47657076c69d766e0399980dce1b258c93c3ca23b2020e99b23928cdd95"

      def install
        bin.install "lokey"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.2/lokey-cli_0.2_linux_arm64.tar.gz"
      sha256 "fb234938d913110ab418f559342d5fcc62e913d132f62986881c2b7d127e8d63"

      def install
        bin.install "lokey"
      end
    end
  end
end
