# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lokey < Formula
  desc "A powerful CLI tool for managing Lokey operations"
  homepage "https://github.com/ThywillJoshua/lokey-cli"
  version "0.6"

  depends_on "go"
  depends_on :linux

  if Hardware::CPU.intel?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.6/lokey-cli_0.6_linux_amd64.tar.gz"
      sha256 "2f6e7c79a666826c6200cdc7a076393af5a695893fab87f747ff4a79492695e9"

      def install
        bin.install "lokey"
      end
    end
  end
  if Hardware::CPU.arm?
    if Hardware::CPU.is_64_bit?
      url "https://github.com/ThywillJoshua/lokey-cli/releases/download/v0.6/lokey-cli_0.6_linux_arm64.tar.gz"
      sha256 "e0c992e0ac0f59590503a6c001767029775472384af707e3da10ef66a1153e28"

      def install
        bin.install "lokey"
      end
    end
  end
end
